# Generated by Django 2.0 on 2018-06-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesforuser',
            options={'permissions': (('can_access_hr', 'Can Access the HR portal'),)},
        ),
    ]
