# Generated by Django 2.0 on 2018-06-03 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180603_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_date',
            field=models.DateField(default=datetime.date(2018, 6, 3)),
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 19, 31, 2, 158928)),
        ),
    ]
