# Generated by Django 2.0 on 2018-06-03 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180603_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 20, 6, 57, 658197)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interviewed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
