# Generated by Django 2.0 on 2018-06-03 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180603_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='added_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 20, 7, 53, 171516)),
        ),
    ]
