# Generated by Django 2.0 on 2018-06-04 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20180603_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='applying_for',
            field=models.TextField(choices=[('QA', 'QA'), ('DEV', 'DEV'), ('BA', 'BA'), ('HR', 'HR')], default='DEV'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_date',
            field=models.DateField(default=datetime.date(2018, 6, 4)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 20, 23, 53, 11423)),
        ),
    ]
